In [4]:
from datetime import datetime
import pandas as pd

In [2]:
start = datetime(2022,7,1)
end = datetime(2022,7,30)

In [5]:
df = pd.read_csv('April-22 - Capacity Planning Dispatch Hourly Data.csv')
df.head()

,time_slot,n_distributor_id,dist_name,scan_date,challan_count,total_line_items,item_value,quantity,scan_data,hour,active_hour,previous_day_pending_quantum,actual_quantum,left_quantum,current_quantum,pending_quantum,total_quantum,manpower
0,2022-04-01 01:00:00,36834.0,AK Pharma - Belgaum,2022-04-01,0.0,0.0,0.0,0.0,0,1,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,2022-04-01 02:00:00,36834.0,AK Pharma - Belgaum,2022-04-01,0.0,0.0,0.0,0.0,0,2,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,2022-04-01 03:00:00,36834.0,AK Pharma - Belgaum,2022-04-01,0.0,0.0,0.0,0.0,0,3,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,2022-04-01 04:00:00,36834.0,AK Pharma - Belgaum,2022-04-01,0.0,0.0,0.0,0.0,0,4,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4,2022-04-01 05:00:00,36834.0,AK Pharma - Belgaum,2022-04-01,0.0,0.0,0.0,0.0,0,5,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
df['scan_date'] = pd.to_datetime(df['scan_date'])

In [17]:
df['weekday'] = df['scan_date'].dt.day_name()

In [19]:
df['weekday'].unique()

array(['Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday',
       'Thursday'], dtype=object)